"use client"

import { Star, Quote } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"

interface Testimonial {
  id: string
  name: string
  role: string
  company: string
  content: string
  rating: number
  avatar?: string
}

const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Alfredo H.",
    role: "Repeat Client",
    company: "United States",
    content: "It was great working with sam, he is very responsive and is very knowledgeable on website design and implementation. Is because there are people like sam in fiverr that USA company like to contract with contractors in fiverr, very professional, polite and responsive.",
    rating: 5,
  },
  {
    id: "2",
    name: "Alfredo H.",
    role: "Repeat Client",
    company: "United States",
    content: "sam is awsome he goes above and beyond the requirements and is very respectful. I will hire him again. I addition he has very good sense of what a good looking website should look like.",
    rating: 5,
  },
  {
    id: "3",
    name: "M. Skirton",
    role: "Client",
    company: "United States",
    content: "Working with Sam was a fantastic experience from start to finish. He demonstrated deep understanding, professionalism, and excellent attention to detail while building out our website. Communication was clear, revisions were prompt, and he went above and beyond to make sure everything was just right.",
    rating: 5,
  },
  {
    id: "4",
    name: "Alfredo H.",
    role: "Repeat Client",
    company: "United States",
    content: "the final product was exactly what i requested. He went beyond what i had requested and did several iterations of revisions. Moreover, he is knowledgeable and takes proactive actions; for example, when there were multiple duplicate fields in a csv file generated by a service I contracted he send out...",
    rating: 5,
  },
  {
    id: "5",
    name: "Alfredo H.",
    role: "Repeat Client",
    company: "United States",
    content: "He was amazing and knowledgeable and very quick. also was flexible with my revisions. Will defintely hire him again.",
    rating: 5,
  },
  {
    id: "6",
    name: "jesusquesillo",
    role: "Client",
    company: "Colombia",
    content: "Gracias hermano, por toda la amabilidad y por la lealtad que es algo que mucho no tiene, la palabra es una sola y cuando hacemos las cosas bien siempre el mundo irá a nuestro favor 🙏",
    rating: 5,
  },
]

export default function Testimonials() {
  return (
    <section id="testimonials" className="py-24 relative">
      <div className="container mx-auto px-4">
        <div className="mb-16 text-center">
          <h2 className="relative mb-4 inline-block text-4xl font-bold text-white">
            What People Say
            <span className="absolute -bottom-3 left-1/2 h-1 w-12 -translate-x-1/2 rounded bg-emerald-500"></span>
          </h2>
          <p className="text-gray-400 max-w-2xl mx-auto">
            Testimonials from colleagues, professors, and clients about my work and collaboration
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {testimonials.map((testimonial, index) => (
            <div key={testimonial.id}>
              <Card className="h-full bg-gray-900/50 border-gray-800 hover:border-emerald-900 transition-all duration-300 hover:bg-gray-800/50 flex flex-col">
                <CardContent className="p-6 flex flex-col h-full">
                  <div className="flex items-center mb-4">
                    <Quote className="h-8 w-8 text-emerald-400 mr-3" />
                    <div className="flex">
                      {[...Array(testimonial.rating)].map((_, i) => (
                        <Star key={i} className="h-4 w-4 text-yellow-400 fill-current" />
                      ))}
                    </div>
                  </div>
                  
                  <p className="text-gray-300 mb-6 leading-relaxed flex-grow">
                    "{testimonial.content}"
                  </p>
                  
                  <div className="flex items-center mt-auto">
                    <div className="w-12 h-12 bg-emerald-600 rounded-full flex items-center justify-center mr-4 flex-shrink-0">
                      <span className="text-white font-bold text-lg">
                        {testimonial.name.charAt(0)}
                      </span>
                    </div>
                    <div>
                      <h4 className="font-semibold text-white">{testimonial.name}</h4>
                      <p className="text-sm text-emerald-400">{testimonial.role}</p>
                      <p className="text-sm text-gray-400">{testimonial.company}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          ))}
        </div>

        <div className="text-center mt-12">
          <p className="text-gray-400 mb-4">
            Want to work together? Let's discuss your project!
          </p>
          <a
            href="#contact"
            className="inline-flex items-center px-6 py-3 bg-emerald-600 text-white font-medium rounded-lg hover:bg-emerald-700 transition-colors duration-200"
          >
            Get In Touch
          </a>
        </div>
      </div>
    </section>
  )
} 